#!/bin/bash

printf "\033[0;36m############################### START ###############################\033[0m\n"
docker start tpe
docker exec -it tpe make -C /root/Toolchain clean
docker exec -it tpe make -C /root clean
docker exec -it tpe make -C /root/Toolchain all
docker exec -it tpe make -C /root all
docker stop tpe
printf "\033[0;36m############################### END ###############################\033[0m\n"

if [ $# -eq 1 ] && [ $1 == "run" ]
then
	cd /home/nehuenllanos/Desktop/TPE/tpe-arqui
	sudo ./run.sh
fi
